"""
Clinical Recommendation Data Models and Service Layer.

This module defines request/response schemas for the clinical recommendation
pipeline along with safe initialization utilities and structured logging.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Union, Optional

from pydantic import BaseModel, Field, ValidationError


# ---------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------

DEFAULT_AI_CERTAINTY: str = "High"
LOG_NAME: str = "clinical_recommendation_service"


# ---------------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------------

def configure_logging() -> logging.Logger:
    """
    Configure structured logging for the service.

    Returns
    -------
    logging.Logger
        Configured logger instance.
    """
    logger = logging.getLogger(LOG_NAME)

    if not logger.handlers:
        logger.setLevel(logging.INFO)

        handler = logging.StreamHandler()

        formatter = logging.Formatter(
            fmt=(
                "%(asctime)s | %(levelname)s | %(name)s | "
                "%(filename)s:%(lineno)d | %(message)s"
            )
        )

        handler.setFormatter(formatter)
        logger.addHandler(handler)

    return logger


logger = configure_logging()


# ---------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------

class PatientData(BaseModel):
    """
    Patient clinical data used for generating medical recommendations.
    """

    age: Optional[int] = Field(default=None, description="Patient age")
    gender: Optional[str] = Field(default=None, description="Patient gender")

    hba1c: Optional[float] = Field(
        default=None,
        description="HbA1c level used for diabetes assessment",
    )

    bp_systolic: Optional[int] = Field(
        default=None,
        description="Systolic blood pressure",
    )

    bp_diastolic: Optional[int] = Field(
        default=None,
        description="Diastolic blood pressure",
    )

    weight: Optional[float] = Field(
        default=None,
        description="Patient weight in kilograms",
    )

    history: Optional[str] = Field(
        default="",
        description="Relevant medical history",
    )

    raw_summary: str = Field(
        ...,
        description="Unstructured clinical summary from EHR or notes",
    )


class Recommendation(BaseModel):
    """
    Individual clinical recommendation generated by the system.
    """

    title: str
    strength: str
    reasoning: str

    citation_source: str
    citation_section: str

    ai_certainty: Union[str, float, int, Any] = Field(
        default=DEFAULT_AI_CERTAINTY,
        description="Model certainty level",

    ) 

    reliability_score: float

    source_chunks: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Retrieved knowledge chunks used for reasoning",
    )


class RecommendationResponse(BaseModel):
    """
    Final response returned to the API consumer.
    """

    clinical_summary: str

    risk_factors: List[str]

    retrieved_chunks: List[Dict[str, Any]]

    recommendations: List[Recommendation]

    confidence_score: float


# ---------------------------------------------------------------------
# Service Layer
# ---------------------------------------------------------------------

class RecommendationService:
    """
    Service responsible for processing patient data
    and producing recommendation responses.
    """

    def __init__(self) -> None:
        """
        Initialize the service safely.
        """
        try:
            logger.info("Initializing RecommendationService")

            # Future dependencies can be initialized here
            # e.g. vector DB, LLM client, retriever

        except Exception as exc:
            logger.exception("Failed to initialize RecommendationService")
            raise RuntimeError("Service initialization failed") from exc

    def validate_patient_data(self, payload: Dict[str, Any]) -> PatientData:
        """
        Validate incoming patient data payload.

        Parameters
        ----------
        payload : Dict[str, Any]
            Raw input data.

        Returns
        -------
        PatientData
            Validated patient data model.
        """
        try:
            patient_data = PatientData(**payload)
            logger.info("Patient data validation successful")
            return patient_data

        except ValidationError as exc:
            logger.error("Patient data validation failed: %s", exc)
            raise

    def build_response(
        self,
        summary: str,
        risks: List[str],
        chunks: List[Dict[str, Any]],
        recommendations: List[Recommendation],
        confidence: float,
    ) -> RecommendationResponse:
        """
        Construct the final recommendation response.

        Returns
        -------
        RecommendationResponse
        """
        try:
            response = RecommendationResponse(
                clinical_summary=summary,
                risk_factors=risks,
                retrieved_chunks=chunks,
                recommendations=recommendations,
                confidence_score=confidence,
            )

            logger.info("Recommendation response generated")
            return response

        except Exception as exc:
            logger.exception("Failed to construct recommendation response")
            raise RuntimeError("Response generation failed") from exc